FROM edge-base-raspberry
    
ARG root=endpoints/lock
WORKDIR /usr/src/
COPY ${root}/requirements.rpi4.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY ${root}/app.py ./
COPY models ./models
COPY common ./common
COPY lock ./lock
COPY api ./api
COPY ${root}/start.sh ./
RUN chmod +x start.sh
ENV RPI=1

ENTRYPOINT [ "./start.sh" ]