FROM cloud-base

ARG root=endpoints/repository
WORKDIR /usr/src/
COPY ${root}/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY api/ ./api/
COPY common/ ./common/
COPY ${root}/app.py ./
COPY ${root}/start.sh ./
RUN chmod +x start.sh
ENTRYPOINT [ "./start.sh" ]